fix: Workaround for Mizrahi bank API bug which returns transactions before the start date
eshaham/israeli-bank-scrapers pull request #606
Opened 2021-09-11 19:01 UTC by alonl

For some reason Mizrahi bank API returns transactions before the requested "from" date (start date). From what I've noticed, usually it is one additional transaction, and it doesn't matter what its date is.

With YNAB exporter in [Caspion](https://github.com/brafdlog/caspion) it does a real mess since it makes those transactions being imported again and again and creates duplicates.

This fix is a workaround for this bug of Mizrahi Bank API which double checks the transaction date is within range.

2021-09-13 06:37 UTC, eshaham requested changes
Thanks for contributing 😄 
Question about the bug with the bank's API - are the transactions returned missed by more than one day?
Meaning, if I specify the start date as 10/7, will it also return transactions from 5/7?

2021-09-13 06:37 UTC, eshaham commented on src/scrapers/mizrahi.ts
> +    const oshTxnAfterStartDate = oshTxn.filter(txn => !moment(txn.date).isBefore(startMoment));
```suggestion
    const oshTxnAfterStartDate = oshTxn.filter(txn => moment(txn.date). isSameOrAfter(startMoment));
```

2021-09-18 21:53 UTC, alonl commented
> Thanks for contributing 
> Question about the bug with the bank's API - are the transactions returned missed by more than one day?
> Meaning, if I specify the start date as 10/7, will it also return transactions from 5/7?

Thank you! 
Yes. From my observation it seems that it returns one additional transaction, which is the last one that's happened before the start date. It can be one day before or even 2 weeks.

2021-09-19 03:39 UTC, eshaham commented
@alonl the lint job is failing - can you run `npm run lint` locally and fix the lint errors?

2021-09-25 07:17 UTC, alonl commented
> @alonl the lint job is failing - can you run `npm run lint` locally and fix the lint errors?

Fixed, sorry.

2021-09-26 19:56 UTC, eshaham approved these changes
looking good, thanks 👌

2021-09-26 19:56 UTC, merged