feat(mizrahi): scrape extra info
eshaham/israeli-bank-scrapers pull request #890
Opened 2024-11-22 22:07 UTC by simonlsk

Should solve #784. 

## Changes:
* Extract Cookie from main page request.
* Fetch extra details request (endpoint `/Online/api/OSH/getMaherBerurimSMF`) if `additionalTransactionInformation` is `true`.
* Concatenate details in `txn.memo` in the format `field1: value1; field2: value2; ...;`

# Status and todos:
- [x] Tests passing locally.
- [ ] Not sure about the returned memo format.
- [ ] Check if there is a cleaner way to extract the cookie and use it in my requests.
- [ ] Not stressed tested on many transactions.

I don't have a lot of experience with `puppeteer`, would love to get some inputs about the unchecked boxes. 

Thanks

2024-11-24 06:33 UTC, baruchiro commented
Thank you, I hope I will review it soon

2024-11-24 06:33 UTC, baruchiro commented
Can I list you as a code owner for Mizrahi https://github.com/eshaham/israeli-bank-scrapers/issues/830?

2025-01-28 06:14 UTC, baruchiro requested changes

2025-01-28 06:14 UTC, baruchiro commented on src/scrapers/mizrahi.ts
> +    .filter(({ record }) => record.MC02ShowDetailsEZ === '1');
Better to filter and then map

2025-01-28 06:14 UTC, baruchiro commented on src/scrapers/mizrahi.ts
> +async function getExtraScrap(originalRecords: ScrapedTransaction[], currentTxns: Transaction[], headers: Headers): Promise<Transaction[]> {
rename to `addExtraInfo`

2025-01-28 06:14 UTC, baruchiro commented on src/scrapers/mizrahi.ts
> +  }
I think you're trying to do a batch proccesing here, but you missed something.

Once you run an `async` function, it runs! When you called `getTransactionExtraScrap(record, headers)`, the function executed. It happened on the function **call** and not on the `await` call.

In your code, the `promises` hold **all the executions**, and you just **waiting** them one-by-one, it is not logical.

2025-01-28 06:14 UTC, baruchiro commented on src/scrapers/mizrahi.ts
> +  });
I guess you want to clone the current transaction, what do you think about this?


```suggestion
  const txnsWithExtra = currentTxns.map(({ ...currentTxn }, i) => {
    const extraDetailIndex = recordsWithDetails.findIndex(({ index }) => index === i);
    const extraDetails = extraDetailIndex !== -1 ? accounts[extraDetailIndex] : undefined;

    if (extraDetails) {
      currentTxn.memo = simplifyExtraTransactionResultsToMemo(extraDetails);
    }
    return currentTxn;
  });
```

2025-01-28 06:14 UTC, baruchiro commented on src/scrapers/mizrahi.ts
> +}
I'm not sure we want to build a memo by ourself.

Maybe you can add an example of an object and we can learn what are you building here.

2025-01-28 06:14 UTC, baruchiro requested changes
Thank you for your contribution!!

2025-02-02 12:35 UTC, simonlsk commented
Thanks for the review, I'll make the fixes as soon as I can.

2025-04-19 02:01 UTC, closed without merging